name: Test Suite

on: [push, pull_request]

jobs:
  build:

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9]
        include:
          - os: windows-latest
            python-version: 3.9
          - os: windows-latest
            python-version: 2.7

    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip
    - uses: actions/checkout@v2
    - name: Install with test dependencies
      shell: bash
      run: |
        # Currently required see GH issues: bbc/vc2_conformance#7 and
        # bbc/vc2_conformance_data#5
        python -m pip install "vc2_conformance_data @ https://github.com/bbc/vc2_conformance_data/releases/download/v1.0.0/vc2_conformance_data.tar.gz"
        python setup.py develop
        python -m pip install -r requirements-test.txt
    - name: Run test suite
      run: |
        py.test tests/
